version: 2.1
executors:
  snakeplanner_publisher:
    environment:
      IMAGE_NAME: oldrover/snakeplanner
    docker:
      - image: cimg/openjdk:11.0

jobs:
  build_and_test:
    executor: snakeplanner_publisher   
    steps:
      - checkout
      - setup_remote_docker
      - run: git submodule sync
      - run: git submodule update --remote --recursive      
      - run:
          name: Build and Test
          command: ./mvnw package    

  publish:
    executor: snakeplanner_publisher
    steps:
      - checkout
      - setup_remote_docker
      

# invoking jobs via workflows
workflows:
  snakeplanner_build_test_deploy:
    jobs:
      - build_and_test
      - publish:
          requires:
            - build_and_test
     